fsck: fix bad char check for non-ASCII characters
Invalid filename characters in the exfat specification are
defined in UTF16 format. We need to convert the file name
to UTF16 format and then check it is valid, otherwise the
input file name containing non-ASCII characters will be
incorrectly checked as invalid.

Such as:

$ fsck.exfat -r exfat.img
exfatprogs version : 1.2.4
ERROR: '..' filename is not allowed.
 [1] Insert the name you want to rename.
 [2] Automatically renames filename.
 [3] Bypass this check(No repair)
Select (Number: ?) 1
New name: 点点
filename contain invalid character(�)

Signed-off-by: Yuezhang Mo <Yuezhang.Mo@sony.com>
Reviewed-by: Aoyama Wataru <wataru.aoyama@sony.com>
Reviewed-by: Hyunchul Lee <hyc.lee@gmail.com>
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>