lib: support 512 bytes cluster size
From exFAT specification, the cluster size lower limit is 512
bytes. But if cluster size is 512 bytes, fsck will corrupt good
files in the following case.

$ mount exfat.img /mnt/test/
$ mkdir /mnt/test/dir
$ touch /mnt/test/dir/$(tr -cd '[:alnum:]' </dev/urandom | head -c 180)
$ touch /mnt/test/dir/$(tr -cd '[:alnum:]' </dev/urandom | head -c 255)
$ umount /mnt/test
$ fsck.exfat exfat.img
exfatprogs version : 1.2.2
ERROR: /dir: the checksum of a file is wrong at 0x201dc0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc0 at 00001e0 at 0x201de0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000200 at 0x201e00. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000220 at 0x201e20. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000240 at 0x201e40. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000260 at 0x201e60. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000280 at 0x201e80. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00002a0 at 0x201ea0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00002c0 at 0x201ec0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00002e0 at 0x201ee0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000300 at 0x201f00. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000320 at 0x201f20. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000340 at 0x201f40. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000360 at 0x201f60. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000380 at 0x201f80. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00003a0 at 0x201fa0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00003c0 at 0x201fc0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 00003e0 at 0x201fe0. Delete (y/N)? n
ERROR: /dir: unknown entry type 0xc1 at 0000400 at 0x202000. Delete (y/N)? n
exfat.img: corrupted. directories 2, files 1
exfat.img: files corrupted 1, files fixed 0

The cause is exfat_de_iter->buffer_desc only caches two clusters
or two 4096-byte buffers, the dentries in a dentry set may be in
3~16 clusters or three 4096-byte buffers.

This commit makes exfat_de_iter->buffer_desc to cache at least
272=256+512/DENTRY_SIZE dentries. Even if a dentry set has 256
dentries, it can be cached in exfat_de_iter->buffer_desc.

Signed-off-by: Yuezhang Mo <Yuezhang.Mo@sony.com>
Acked-by: Hyunchul Lee <hyc.lee@gmail.com>
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>